#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
    configure)

        # Enable the kernel module
        modprobe v4l2loopback-dc

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
