#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)

        # Disable the kernel module
        modprobe --remove v4l2loopback-dc

    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
